name: main

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.0'
    
    - name: Install dependencies
      run: |
        go version
        make deps
      
    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        make lint
        make vet
    
    # Run testing on the code
    - name: Run testing
      run: make test-cover
